Add integrations fix n+1
vflorin1995/Rails_Blog pull request #8
Opened 2023-01-30 20:17 UTC by vflorin1995

### Changes:

- Add integration tests for all 4 classes
- Optimize the n+1 query

![file_1_before](https://user-images.githubusercontent.com/108400762/215585608-4a52fd88-1388-4d8b-827f-1f11e77e25c6.jpg)
![file_1_after](https://user-images.githubusercontent.com/108400762/215585627-959c4272-40a0-4df7-95f1-89026b36e9ba.png)
![file_2_before](https://user-images.githubusercontent.com/108400762/215585657-99f1f2a7-a768-4c8d-88ea-72f04a2aa344.jpg)
![file_2_after](https://user-images.githubusercontent.com/108400762/215585679-0439d15c-e063-4169-b31b-7d063c964247.png)

2023-01-30 21:08 UTC, mikethreels requested changes
Hi Florin, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 21:08 UTC, mikethreels commented on spec/views/users/show.html.erb_spec.rb
> +      visit user_path(subject)
- [ ] please put an `it` block before each test with a description of what the particular test is testing.

2023-01-30 21:08 UTC, mikethreels commented on spec/views/users/index.html.erb_spec.rb
> +end
- [ ] please put an `it` block before each test with a description of what the particular test is testing.

2023-01-30 21:08 UTC, mikethreels commented on spec/views/posts/show.html.erb_spec.rb
> +    end
- [ ] please put an `it` block before each test with a description of what the particular test is testing.

2023-01-30 21:08 UTC, mikethreels commented on spec/views/posts/index.html.erb_spec.rb
> +
- [ ] please put an `it` block before each test with a description of what the particular test is testing.

2023-01-31 08:43 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @vflorin1995, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Good job with test coverage
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 08:45 UTC, merged